DROP TYPE IF EXISTS mood;
CREATE TYPE mood AS ENUM (
  'sad', 
  'meh', 
  'happy'
);

CREATE TABLE meditations (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  description TEXT NOT NULL,
  minutes INTEGER DEFAULT 5,
  current_mood mood NOT NULL,
  notes TEXT NOT NULL,
  date TIMESTAMPTZ DEFAULT now() NOT NULL
);