-- do I need to add in the minutes or date, or since it's default it doesn't need to be seeded and will default?

TRUNCATE meditations;

INSERT INTO meditations (description, minutes, notes, date, mood)
('Happy Hopeful Excited', 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum voluptatum vitae atque animi nesciunt illo, eius harum. Libero at minus debitis modi id unde est commodi! Eligendi esse nisi accusamus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit laudantium atque a distinctio, numquam incidunt nemo, neque nihil id tempora ad. Deleniti porro voluptates nulla itaque suscipit optio iure dolor. Lorem ipsum dolor sit amet consectetur adipisicing elit.', 'happy'),
('Sad Anxious Confused', 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum voluptatum vitae atque animi nesciunt illo, eius harum. Libero at minus debitis modi id unde est commodi! Eligendi esse nisi accusamus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit laudantium atque a distinctio, numquam incidunt nemo, neque nihil id tempora ad. Deleniti porro voluptates nulla itaque suscipit optio iure dolor. Lorem ipsum dolor sit amet consectetur adipisicing elit.', 'sad'),
('Medium Unsure', 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum voluptatum vitae atque animi nesciunt illo, eius harum. Libero at minus debitis modi id unde est commodi! Eligendi esse nisi accusamus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit laudantium atque a distinctio, numquam incidunt nemo, neque nihil id tempora ad. Deleniti porro voluptates nulla itaque suscipit optio iure dolor. Lorem ipsum dolor sit amet consectetur adipisicing elit.', 'meh'),
('Energized Focused Inspired', 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum voluptatum vitae atque animi nesciunt illo, eius harum. Libero at minus debitis modi id unde est commodi! Eligendi esse nisi accusamus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit laudantium atque a distinctio, numquam incidunt nemo, neque nihil id tempora ad. Deleniti porro voluptates nulla itaque suscipit optio iure dolor. Lorem ipsum dolor sit amet consectetur adipisicing elit.', 'happy'),
('Sleep', 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum voluptatum vitae atque animi nesciunt illo, eius harum. Libero at minus debitis modi id unde est commodi! Eligendi esse nisi accusamus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit laudantium atque a distinctio, numquam incidunt nemo, neque nihil id tempora ad. Deleniti porro voluptates nulla itaque suscipit optio iure dolor. Lorem ipsum dolor sit amet consectetur adipisicing elit.', 'meh');